[package]
name = "wasm-gol"
description = "game of life implemented in rust using webassembly"
version = "0.1.0"
authors = ["cubedhuang <99danielh@gmail.com>"]
license = "GNU/GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
